apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.drn }}-{{ lower .Values.executionId | replace "-" "" | replace "_" "" | substr 0 3 }}
  labels:
    name: {{ .Values.drn }}-{{ lower .Values.executionId | replace "-" "" | replace "_" "" | substr 0 3 }}
